"""YouTube transcript scraper — fetches captions for top videos per brand.

Selection: per brand, top N videos by view_count where is_short = false,
excluding videos that already have a transcript row fetched within the
TRANSCRIPT_REFRESH_DAYS window.

Missing transcripts MUST NOT break the pipeline — they're written with
fetch_status='no_transcript' so downstream analysis can still run from
title + description.
"""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any
from urllib.parse import quote

from ...core import apify_client as apify
from ...core import supabase_client as sb
from ...core.errors import ActorRunError, ActorStartError
from ...core.logger import get_logger

log = get_logger("yt.transcripts")

ACTOR_ID = "pintostudio/youtube-transcript-scraper"
TOP_PER_BRAND = 25
MIN_VIEWS = 1000
TRANSCRIPT_REFRESH_DAYS = 30
MAX_WORKERS = 5  # parallel actor runs (each takes ~10-40s)


def _existing_youtube_ids() -> set[str]:
    """Return youtube_video_ids whose latest row is fresh AND not in error state.

    Rows with fetch_status='error' get retried — they typically indicate a
    transient actor / network problem rather than a real "no captions" verdict.
    """
    try:
        # URL-encode the timestamp so the '+' in '+00:00' isn't decoded as space
        recent = quote(_recent_iso(TRANSCRIPT_REFRESH_DAYS), safe="")
        rows = sb.get_filtered(
            "yt_video_transcripts",
            "youtube_video_id,fetched_at,fetch_status",
            f"fetched_at=gte.{recent}&fetch_status=in.(ok,no_transcript,private)&limit=10000",
        )
        return {r["youtube_video_id"] for r in rows}
    except Exception as e:
        log.warning("Could not pre-load existing transcripts: %s", e)
        return set()


def _recent_iso(days: int) -> str:
    from datetime import datetime, timedelta, timezone
    return (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()


def _pick_videos(brand_ids: set[str] | None, limit_override: int | None) -> list[dict]:
    """Top N videos per brand by view_count, long-form only."""
    rows = sb.get_filtered(
        "yt_videos",
        "id,brand_id,youtube_video_id,video_url,title,view_count",
        f"is_short=eq.false&view_count=gte.{MIN_VIEWS}&order=view_count.desc&limit=2000",
    )
    if brand_ids:
        rows = [r for r in rows if r.get("brand_id") in brand_ids]

    per_brand: dict[str, list[dict]] = {}
    for r in rows:
        per_brand.setdefault(r.get("brand_id") or "_none", []).append(r)

    cap = limit_override or TOP_PER_BRAND
    out: list[dict] = []
    for bid, lst in per_brand.items():
        out.extend(lst[:cap])
    return out


def _extract_transcript(item: dict) -> tuple[str | None, str, str | None, list | None, bool]:
    """Normalize one Apify result row.

    Returns: (transcript_text, fetch_status, language, segments, is_auto_generated)
    """
    # Explicit error / unavailable signals
    err = (item.get("error") or "").lower()
    if "no_transcript" in err or "no transcript" in err or "captions" in err:
        return None, "no_transcript", None, None, False
    if "private" in err or "unavailable" in err or "removed" in err:
        return None, "private", None, None, False
    if "rate" in err or "quota" in err:
        return None, "rate_limited", None, None, False

    segments = item.get("transcript") or item.get("captions") or item.get("segments")
    if isinstance(segments, list) and segments and isinstance(segments[0], dict):
        text = " ".join(s.get("text", "") for s in segments).strip()
    elif isinstance(segments, list):
        text = " ".join(str(s) for s in segments).strip()
        segments = None
    else:
        text = (item.get("text") or item.get("transcriptText") or "").strip()
        segments = None

    if not text:
        return None, "no_transcript", item.get("language"), None, False

    return (
        text,
        "ok",
        item.get("language") or item.get("lang"),
        segments if isinstance(segments, list) else None,
        bool(item.get("isAutoGenerated") or item.get("auto_generated") or False),
    )


def run(ctx: dict[str, Any]) -> int:
    dry_run: bool = ctx.get("dry_run", False)
    brand_filter: list[str] | None = ctx.get("brands")
    limit_override: int | None = ctx.get("limit")

    brand_ids: set[str] | None = None
    if brand_filter:
        brand_rows = sb.get("brands", "id,slug")
        brand_ids = {r["id"] for r in brand_rows if r["slug"] in brand_filter}
        if not brand_ids:
            log.warning("No brands matched filter %s", brand_filter)
            return 0

    videos = _pick_videos(brand_ids, limit_override)
    if not videos:
        log.info("No eligible videos for transcript fetch")
        return 0

    seen = _existing_youtube_ids()
    todo = [v for v in videos if v.get("youtube_video_id") not in seen and v.get("video_url")]
    log.info("Transcript queue: %d videos (skipping %d with fresh transcripts)",
             len(todo), len(videos) - len(todo))

    if not todo:
        return 0

    if dry_run:
        log.info("[DRY-RUN] would fetch transcripts for %d videos via %s", len(todo), ACTOR_ID)
        return 0

    rows: list[dict] = []
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
        futures = {ex.submit(_fetch_one, v): v for v in todo}
        for fut in as_completed(futures):
            v = futures[fut]
            try:
                rows.append(fut.result())
            except Exception as e:
                log.error("Unexpected error for %s: %s", v.get("youtube_video_id"), e)
                rows.append(_row_from_video(v, fetch_status="error", fetch_error=str(e)[:300]))

    if not rows:
        return 0

    n = sb.upsert("yt_video_transcripts", rows, "youtube_video_id")
    ok = sum(1 for r in rows if r["fetch_status"] == "ok")
    missing = sum(1 for r in rows if r["fetch_status"] == "no_transcript")
    log.info("✓ %d transcripts upserted (%d ok, %d no_transcript, %d errors)",
             n, ok, missing, n - ok - missing)
    return n


def _fetch_one(v: dict) -> dict:
    """Call pintostudio actor for a single video. Always returns a row dict."""
    url = v["video_url"]
    try:
        items = apify.run_and_fetch(ACTOR_ID, {"videoUrl": url})
    except (ActorStartError, ActorRunError) as e:
        return _row_from_video(v, fetch_status="error", fetch_error=str(e)[:300])

    if not items:
        return _row_from_video(v, fetch_status="no_transcript")

    text, status, lang, segments, auto = _extract_transcript(items[0])
    return _row_from_video(
        v, transcript_text=text, fetch_status=status,
        language=lang, segments=segments, is_auto_generated=auto,
    )


def _row_from_video(
    v: dict,
    *,
    transcript_text: str | None = None,
    fetch_status: str = "ok",
    language: str | None = None,
    segments: list | None = None,
    is_auto_generated: bool = False,
    fetch_error: str | None = None,
) -> dict:
    word_count = len(transcript_text.split()) if transcript_text else 0
    char_count = len(transcript_text) if transcript_text else 0
    return {
        "video_id":          v["id"],
        "youtube_video_id":  v["youtube_video_id"],
        "brand_id":          v.get("brand_id"),
        "language":          language,
        "is_auto_generated": is_auto_generated,
        "transcript_text":   transcript_text,
        "segments":          segments,
        "word_count":        word_count,
        "char_count":        char_count,
        "source_actor":      ACTOR_ID,
        "fetch_status":      fetch_status,
        "fetch_error":       fetch_error,
    }
